import {StyleSheet} from 'react-native';

export const useStyles = (color: any) =>
  StyleSheet.create({
    tabsContainer: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    tabsItemFocused: {
      backgroundColor: color.primaryLighter90,
      borderWidth: 2,
      borderColor: color.primary,
      borderRadius: 12,
      paddingHorizontal: 13,
      paddingVertical: 8,
      marginRight: 8,
      alignItems: 'center',
      justifyContent: 'center',
      width: 115,
    },
    tabAllFocused: {
      backgroundColor: color.primaryLighter90,
      borderWidth: 2,
      borderColor: color.primary,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 9,
      marginRight: 6,
      alignItems: 'center',
      justifyContent: 'center',
      width: 50,
    },
    tabsItemUnfocused: {
      backgroundColor: color.netralWhite,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: color.tertiary,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 9,
      marginRight: 8,
      width: 115,
    },
    tabAllUnfocused: {
      backgroundColor: color.netralWhite,
      borderWidth: 2,
      borderColor: color.tertiary,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 9,
      marginRight: 6,
      alignItems: 'center',
      justifyContent: 'center',
      width: 50,
    },
    textActive: {
      fontFamily: 'HelveticaNeueMedium',
      fontSize: 12,
      lineHeight: 16.8,
      letterSpacing: 0.5,
      color: color.primary,
      textAlign: 'center',
    },
    textInactive: {
      fontFamily: 'HelveticaNeueRoman',
      fontSize: 12,
      lineHeight: 16.8,
      letterSpacing: 0.5,
      color: color.tertiaryDarker60,
      textAlign: 'center',
    },
    label: {
      fontFamily: 'HelveticaNeueMedium',
      fontSize: 18,
      lineHeight: 21.6,
      letterSpacing: 0.5,
      color: color.text,
      marginBottom: 12,
    },
  });
